baseurl = "/"
enableGitInfo = true
enableRobotsTXT = true
editor = "code"
languageCode = "en-US"
language = "en"
title = "Tony Burns"

[permalinks]
  articles = "articles/:title/"
  notes = "notes/:title/"
  photos = "photos/:title/"