baseurl = "/"
enableGitInfo = true
enableRobotsTXT = true
editor = "code"
languageCode = "en-US"
language = "en"
title = "Tony Burns"
theme = "wilson"

disablePathToLower = true

[permalinks]
  articles = "articles/:slug/"
  audio = "audio/:slug/"
  bookmarks = "bookmarks/:slug/"
  notes = "notes/:slug/"
  photos = "photos/:slug/"
  replies = "replies/:slug/"
  reposts = "reposts/:slug/"
  rsvps = "rsvps/:slug/"
  videos = "videos/:slug/"

[params]
  mainSections = ["articles", "notes", "photos", "videos", "audio", "bookmarks", "likes", "replies", "reposts"]
  citationTypes = ["bookmarks", "likes", "replies", "reposts", "rsvps"]

  [[params.links]]
    rel = "authorization_endpoint"
    href = "https://tonyburns.io/indieauth/authorize"

  [[params.links]]
    rel = "token_endpoint"
    href = "https://tonyburns.io/indieauth/token"

  [[params.links]]
    rel = "micropub"
    href = "https://tonyburns.io/micropub"

  [[params.links]]
    rel = "webmention"
    href = "https://tonyburns.io/webmentions"
