baseurl = "/"
enableGitInfo = true
enableRobotsTXT = true
editor = "code"
languageCode = "en-US"
language = "en"
title = "Tony Burns"
theme = "wilson"

[permalinks]
  articles = "articles/:slug/"
  notes = "notes/:slug/"
  photos = "photos/:slug/"

[params]
  [[params.links]]
    rel = "authorization_endpoint"
    href = "https://tonyburns.io/indieauth/authorize"

  [[params.links]]
    rel = "token_endpoint"
    href = "https://tonyburns.io/indieauth/token"

  [[params.links]]
    rel = "micropub"
    href = "https://tonyburns.io/micropub"

  [[params.links]]
    rel = "webmention"
    href = "https://tonyburns.io/webmentions"
