enableGitInfo = true
enableRobotsTXT = true
editor = "code"
languageCode = "en"
language = "en"
title = "Tony Burns"

[permalinks]
  articles = "articles/:title/"
  notes = "notes/:year/:month/:day/:title"
  photos = "photos/:year/:month/:day/:title"