baseurl = "/"
enableGitInfo = true
enableRobotsTXT = true
editor = "code"
languageCode = "en-US"
language = "en"
title = "Tony Burns"
theme = "wilson"

[permalinks]
  articles = "articles/:slug/"
  notes = "notes/:slug/"
  photos = "photos/:slug/"
